spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/edhumeni
    username: ${SPRING_DATASOURCE_USERNAME:dev}
    password: ${SPRING_DATASOURCE_PASSWORD:development}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8080
  servlet:
    context-path: /api

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    com.edhumeni: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  security:
    jwt:
      secret: ${JWT_SECRET:edhumeni_secret_key_for_development_only_replace_in_production}
      expiration: 86400000 # 24 hours
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics